# Generated by Django 5.2.6 on 2025-09-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Inventory',
            fields=[
                ('Plate_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Car_type', models.CharField(max_length=20)),
                ('Car_brand', models.CharField(max_length=20)),
                ('Manufacturing_date', models.DateField()),
                ('Car_color', models.CharField(max_length=20)),
                ('Price', models.IntegerField()),
                ('Mileage', models.IntegerField()),
            ],
        ),
    ]
